version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
    rebase-strategy: auto
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    rebase-strategy: auto
